# Generated by Django 4.2.19 on 2025-02-27 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('author', models.CharField(max_length=50, verbose_name='Author')),
                ('publisher', models.IntegerField(max_length=50, verbose_name='Publisher')),
                ('price', models.IntegerField(verbose_name='Price')),
            ],
            options={
                'db_table': 'Books',
            },
        ),
    ]
