# Generated by Django 4.2.19 on 2025-02-27 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='publisher',
            field=models.CharField(max_length=50, verbose_name='Publisher'),
        ),
    ]
